spring:
  datasource:
    url: jdbc:mysql://shortline.proxy.rlwy.net:42939/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: WFEAZovufzrUiPHIiTkCulsSANYjqxDv
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect   # ✅ MySQL8Dialect로 변경
        show_sql: true
        format_sql: true

openai:
  api:
    key: ${OPENAI_API_KEY}   # 환경변수에서 가져오기
  model: gpt-4o-mini         # 모델명도 함께 관리 가능
