spring:
  datasource:
    url: jdbc:mysql://metro.proxy.rlwy.net:15294/railway
    username: root
    password: foGfcVvxQmfapXtfREasBMFaeGingCtH

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
